name: Python application Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@3

      - name: setup python
        uses: actions/setup-python@4
        with:
          python-version: '3.10'

      - name: install depedencies
        run: |
          pip install pytest
          
      -name: execute the test script
       run:|
         python -m unittest test.calculator.py
         
        
      

